FROM linkernetworks/minimal-notebook:master-cuda90

LABEL maintainer="Narumi"

# Install PyTorch
RUN conda install --quiet --yes -c pytorch \
    pytorch==0.3.1 \
    torchvision==0.2.0 \
    cuda90 \
    && conda clean -tipsy \
    && fix-permissions $CONDA_DIR

ARG CACHE_DATE
RUN wget https://raw.githubusercontent.com/linkernetworks/aiforge/master/install.sh -O - | bash
