FROM linkernetworks/minimal-notebook:master-cuda90

LABEL maintainer="Narumi"

# Install PyTorch
RUN conda install --quiet --yes -c pytorch \
    pytorch==0.3.1 \
    torchvision==0.2.0 \
    cuda90 \
    && conda clean -tipsy \
    && fix-permissions $CONDA_DIR

ARG CACHE_DATE
ARG SUBMIT_TOOL_NAME=aurora
RUN wget https://raw.githubusercontent.com/linkernetworks/aurora/master/install.sh -O - | bash \
    && move /usr/local/bin/aiforge $SUBMIT_TOOL_NAME