FROM linkernetworks/minimal-notebook:master-gpu

# Install Chainer and CuPy
RUN pip install -U \
    cupy==2.5.0 \
    chainer==3.5.0 \
    && rm -rf ~/.cache/pip

ARG CACHE_DATE
RUN wget https://raw.githubusercontent.com/linkernetworks/aiforge/master/install.sh -O - | bash
