FROM linkernetworks/minimal-notebook:master-gpu
LABEL maintainer="chrisjan"
RUN conda install --quiet --yes -c anaconda \
        caffe-gpu \
        python-lmdb && \
    conda clean -tipsy && \
    fix-permissions $CONDA_DIR

ARG CACHE_DATE
RUN wget https://raw.githubusercontent.com/linkernetworks/aurora/master/install.sh -O - | bash
