FROM linkernetworks/minimal-notebook:master-gpu
LABEL maintainer="chrisjan"
RUN conda install --quiet --yes -c anaconda \
        caffe-gpu \
        python-lmdb && \
    conda clean -tipsy && \
    fix-permissions $CONDA_DIR

ARG CACHE_DATE
ARG SUBMIT_TOOL_NAME=aurora
RUN wget https://raw.githubusercontent.com/linkernetworks/aurora/master/install.sh -O - | bash \
    && if [ "$SUBMIT_TOOL_NAME" != "aurora" ]; then mv /usr/local/bin/aurora /usr/local/bin/$SUBMIT_TOOL_NAME; fi
