FROM linkernetworks/minimal-notebook:master-gpu

LABEL maintainer="Narumi"

# Install Tensorflow
RUN pip install \
    tensorflow-gpu==1.3.0 \
    keras \
    && rm -rf ~/.cache/pip

ARG CACHE_DATE
ARG SUBMIT_TOOL_NAME=aurora
RUN wget https://raw.githubusercontent.com/linkernetworks/aurora/master/install.sh -O - | bash \
    && mv /usr/local/bin/aurora /usr/local/bin/$SUBMIT_TOOL_NAME
