FROM linkernetworks/minimal-notebook:master-gpu

LABEL maintainer="Narumi"

# Install Tensorflow
RUN pip install \
    tensorflow-gpu==1.3.0 \
    keras \
    && rm -rf ~/.cache/pip

ARG CACHE_DATE
RUN wget https://raw.githubusercontent.com/linkernetworks/aiforge/master/install.sh -O - | bash
