FROM linkernetworks/minimal-notebook:master-cuda90

LABEL maintainer="Narumi"

# Install Tensorflow
RUN pip install -U \
    tensorflow-gpu==1.6.0 \
    keras \
    && rm -rf ~/.cache/pip

ARG CACHE_DATE
ARG SUBMIT_TOOL_NAME=aurora
RUN wget https://raw.githubusercontent.com/linkernetworks/aurora/master/install.sh -O - | bash \
    && move /usr/local/bin/aiforge $SUBMIT_TOOL_NAME