FROM linkernetworks/minimal-notebook:master-cuda80
LABEL maintainer="chrisjan"
RUN conda install --quiet --yes -c anaconda \
        caffe-gpu \
        python-lmdb && \
    conda clean -tipsy && \
    fix-permissions $CONDA_DIR
